"use strict";(()=>{var e={};e.id=703,e.ids=[703],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},92048:e=>{e.exports=require("fs")},55315:e=>{e.exports=require("path")},52333:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>g,patchFetch:()=>y,requestAsyncStorage:()=>p,routeModule:()=>f,serverHooks:()=>m,staticGenerationAsyncStorage:()=>d});var o={};r.r(o),r.d(o,{GET:()=>c});var n=r(33691),a=r(29471),l=r(97183),s=r(85141),i=r(17844),u=r(24478);async function c(){let e=await {rules:[{userAgent:"*"}],sitemap:`${i.baseUrl}/sitemap.xml`},t=(0,u.resolveRouteData)(e,"robots");return new s.NextResponse(t,{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=0, must-revalidate"}})}let f=new n.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/robots.txt/route",pathname:"/robots.txt",filename:"robots",bundlePath:"app/robots.txt/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Frobots.txt%2Froute&filePath=%2FUsers%2Fjoel%2Fblog%2Fapp%2Frobots.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:o}),{requestAsyncStorage:p,staticGenerationAsyncStorage:d,serverHooks:m}=f,g="/robots.txt/route";function y(){return(0,l.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:d})}},17844:(e,t,r)=>{r.r(t),r.d(t,{baseUrl:()=>s,default:()=>i});var o=r(92048),n=r.n(o),a=r(55315),l=r.n(a);let s="https://joelhuang.dev";async function i(){let e=(function e(t){let r=[];return n().readdirSync(t).forEach(o=>{let a=l().join(t,o);if(n().statSync(a).isDirectory())r=r.concat(e(a));else if(".mdx"===l().extname(o)){var s;let e,t,o,i,u;let{metadata:c,content:f}=(s=n().readFileSync(a,"utf-8"),t=(e=/---\s*([\s\S]*?)\s*---/).exec(s)[1],o=s.replace(e,"").trim(),i=t.trim().split("\n"),u={},i.forEach(e=>{let[t,...r]=e.split(": "),o=r.join(": ").trim();(o=o.replace(/^['"](.*)['"]$/,"$1"),"tags"===t)?(o=o.slice(1,-1),u.tags=o.split(", ")):u[t]=o}),{metadata:u,content:o}),p=l().basename(a,l().extname(a));r.push({metadata:c,slug:p,content:f})}}),r})(l().join(process.cwd(),"app","blog","posts")).map(e=>({url:`${s}/blog/${e.slug}`,lastModified:e.metadata.publishedAt}));return[...["","/blog"].map(e=>({url:`${s}${e}`,lastModified:new Date().toISOString().split("T")[0]})),...e]}},24478:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveManifest:function(){return l},resolveRobots:function(){return n},resolveRouteData:function(){return s},resolveSitemap:function(){return a}});let o=r(95359);function n(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,o.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,o.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,o.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,o.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function a(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),r="";for(let n of(r+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var o;r+=`<url>
<loc>${n.url}</loc>
`;let e=null==(o=n.alternates)?void 0:o.languages;if(e&&Object.keys(e).length)for(let t in e)r+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(n.lastModified){let e=n.lastModified instanceof Date?n.lastModified.toISOString():n.lastModified;r+=`<lastmod>${e}</lastmod>
`}n.changeFrequency&&(r+=`<changefreq>${n.changeFrequency}</changefreq>
`),"number"==typeof n.priority&&(r+=`<priority>${n.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function l(e){return JSON.stringify(e)}function s(e,t){return"robots"===t?n(e):"sitemap"===t?a(e):"manifest"===t?l(e):""}},95359:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function o(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveArray:function(){return r},resolveAsArrayOrUndefined:function(){return o}})}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[645,164],()=>r(52333));module.exports=o})();